/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;
import jdbc.service.MysqlMahasiswaService;
import jdbc.model.Mahasiswa;
import java.util.List;


/**
 *
 * @author jutt
 */
public class FrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameUtama.class.getName());

    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();
        String[] kolom = {"ID", "NAMA"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(kolom, 0);
        tblMahasiswa.setModel(model);
        tampilDataTabel(); 
    }
    
    // Instansiasi service database
    private MysqlMahasiswaService service = new MysqlMahasiswaService();
    
    private void refreshTabel() {
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) tblMahasiswa.getModel();
    model.setRowCount(0); // kosongkan tabel dulu
    
    java.util.List<jdbc.model.Mahasiswa> list = service.getAll();
    if (list != null) {
        for (jdbc.model.Mahasiswa mhs : list) {
            model.addRow(new Object[]{mhs.getId(), mhs.getNama()});
            }
        }
    }
    
    // Fungsi pembantu untuk merefresh visual JTable
    private void tampilDataTabel() {
        // Ambil data dari database
        List<Mahasiswa> listMhs = service.getAll();
        
        // Setup model untuk JTable (Sesuaikan dengan nama variabel JTable Anda)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMahasiswa.getModel();
        model.setRowCount(0); // Kosongkan tabel terlebih dahulu
        
        // Isi tabel dengan data terbaru
        for (Mahasiswa mhs : listMhs) {
            model.addRow(new Object[]{mhs.getId(), mhs.getNama()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAmbilSemua = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtEditId = new javax.swing.JTextField();
        txtEditNama = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        txtHapusId = new javax.swing.JTextField();
        txtHapusNama = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnResetIndeks = new javax.swing.JButton();
        lblIndexInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nama"
            }
        ));
        jScrollPane1.setViewportView(tblMahasiswa);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Kelola Tabel Mahasiswa");

        btnAmbilSemua.setText("Ambil Semua Data");
        btnAmbilSemua.addActionListener(this::btnAmbilSemuaActionPerformed);

        btnTambah.setText("Tambahkan");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        jLabel2.setText("Nama");

        txtEditId.addActionListener(this::txtEditIdActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        txtHapusId.addActionListener(this::txtHapusIdActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnResetIndeks.setText("Reset Index");
        btnResetIndeks.addActionListener(this::btnResetIndeksActionPerformed);

        lblIndexInfo.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAmbilSemua)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah)
                            .addComponent(txtNama)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnResetIndeks)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblIndexInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtHapusId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHapusNama))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit)
                                    .addComponent(btnHapus)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAmbilSemua)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambah)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHapusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHapusNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetIndeks)
                            .addComponent(lblIndexInfo))))
                .addGap(0, 99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmbilSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbilSemuaActionPerformed
        // TODO add your handling code here:
        refreshTabel();
    }//GEN-LAST:event_btnAmbilSemuaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText().trim();
        if (!nama.isEmpty()) {
            jdbc.model.Mahasiswa mhs = new jdbc.model.Mahasiswa();
            mhs.setNama(nama);
            service.add(mhs);
            refreshTabel();
            txtNama.setText("");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtEditIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditIdActionPerformed

    private void txtHapusIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHapusIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHapusIdActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtEditId.getText().trim());
        String namaBaru = txtEditNama.getText().trim();
    
        jdbc.model.Mahasiswa mhs = new jdbc.model.Mahasiswa();
        mhs.setId(id);
        mhs.setNama(namaBaru);
        service.update(mhs);
        refreshTabel();
        txtEditId.setText("");
        txtEditNama.setText("");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetIndeksActionPerformed
        // TODO add your handling code here:
        service.indexReset();
        lblIndexInfo.setText("Index di reset ke 0");
    }//GEN-LAST:event_btnResetIndeksActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtHapusId.getText().trim());
        service.delete(id);
        refreshTabel();
        txtHapusId.setText("");
        txtHapusNama.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbilSemua;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnResetIndeks;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIndexInfo;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtEditId;
    private javax.swing.JTextField txtEditNama;
    private javax.swing.JTextField txtHapusId;
    private javax.swing.JTextField txtHapusNama;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
